# Generated by Django 5.0.1 on 2024-01-07 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='postDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
