# Generated by Django 5.0.1 on 2024-01-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_post_date_post_postdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='postContent',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='postSubject',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='postType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateField(),
        ),
    ]
