# Generated by Django 5.0.1 on 2024-01-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_content_post_postcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='postImages',
        ),
    ]
