# Generated by Django 5.0.1 on 2024-01-07 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_image_image_postimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='postImages',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
